service: exemplo-lambda2

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  sqsSendQueue:
    handler: handler.sqsSendQueue
  sqsReadQueue:
    handler: handler.sqsReadQueue